[package]
publish = false
name = "aws-credentials"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
doctest = false

[dependencies]
aws-credential-types = { workspace = true }
aws-smithy-types = { workspace = true }
lru-ttl-cache = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
url = { workspace = true }

[lints.rust]
unsafe_code = "allow"
unreachable_pub = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
