[package]
publish = false
name = "aws-sigv4-signing"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
doctest = false

[dependencies]
aws-credential-types = { workspace = true }
aws-sigv4 = { workspace = true, features = ["sign-http"] }
aws-smithy-runtime-api = { workspace = true }
aws-smithy-types = { workspace = true }
http = { workspace = true }
http-request = { path = "../http-request" }
lru-ttl-cache = { path = "../lru-ttl-cache" }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints.rust]
unsafe_code = "allow"
unreachable_pub = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
