[package]
name = "authz-types"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[lib]
doctest = false

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true }

[lints]
workspace = true
